### ISSUE TITLE
Setup tslint

### ISSUE THREAD

**Issue by MikeKovetsky** [Zihfred/angularPlayer#1]
For now, the codestyle is messed a bit. You have some unnecessary identations from start, spaces, etc. So we need a tool to unify a codestyle. This is especially useful for teams to, because it becomes a standart that helps tp read a code.
Install, configure https://www.npmjs.com/package/tslint
And then fix all issues

**Comment by Zihfred** [comment]
Fixed

**Comment by MikeKovetsky** [comment]
Good
